version: "3.8"

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      chrome:
        condition: service_healthy
    environment:
      - SELENIUM_REMOTE_URL=http://chrome:4444/wd/hub
    restart: always
    command: ["python3", "app.py"]  # Ensures Flask app starts

  chrome:
    image: selenium/standalone-chrome
    container_name: selenium_chrome
    ports:
      - "4444:4444"
    shm_size: "2g"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]  # Corrected health check
      interval: 10s
      retries: 3
      start_period: 10s
    restart: always